//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Folder;

export type SiteColumnTitles = {
  __typename?: 'SiteColumnTitles';
  shortStories?: Maybe<Scalars['String']['output']>;
  poems?: Maybe<Scalars['String']['output']>;
  interviews?: Maybe<Scalars['String']['output']>;
  biography?: Maybe<Scalars['String']['output']>;
  references?: Maybe<Scalars['String']['output']>;
  contact?: Maybe<Scalars['String']['output']>;
};

export type SiteBiography = {
  __typename?: 'SiteBiography';
  title: Scalars['String']['output'];
  text: Scalars['String']['output'];
};

export type SiteShortStories = {
  __typename?: 'SiteShortStories';
  title: Scalars['String']['output'];
  text: Scalars['String']['output'];
};

export type SitePoems = {
  __typename?: 'SitePoems';
  title: Scalars['String']['output'];
  text: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
};

export type SiteInterviews = {
  __typename?: 'SiteInterviews';
  title: Scalars['String']['output'];
  text: Scalars['String']['output'];
};

export type SiteReferences = {
  __typename?: 'SiteReferences';
  title: Scalars['String']['output'];
  text: Scalars['String']['output'];
};

export type SiteContactLinks = {
  __typename?: 'SiteContactLinks';
  title: Scalars['String']['output'];
  text: Scalars['String']['output'];
};

export type Site = Node & Document & {
  __typename?: 'Site';
  siteTitle: Scalars['String']['output'];
  infoLabel: Scalars['String']['output'];
  onlyWorkLabel: Scalars['String']['output'];
  columnTitles?: Maybe<SiteColumnTitles>;
  biography?: Maybe<Array<Maybe<SiteBiography>>>;
  shortStories?: Maybe<Array<Maybe<SiteShortStories>>>;
  poems?: Maybe<Array<Maybe<SitePoems>>>;
  interviews?: Maybe<Array<Maybe<SiteInterviews>>>;
  references?: Maybe<Array<Maybe<SiteReferences>>>;
  contactLinks?: Maybe<Array<Maybe<SiteContactLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteColumnTitlesFilter = {
  shortStories?: InputMaybe<StringFilter>;
  poems?: InputMaybe<StringFilter>;
  interviews?: InputMaybe<StringFilter>;
  biography?: InputMaybe<StringFilter>;
  references?: InputMaybe<StringFilter>;
  contact?: InputMaybe<StringFilter>;
};

export type SiteBiographyFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type SiteShortStoriesFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SitePoemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type SiteInterviewsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type SiteReferencesFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type SiteContactLinksFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  siteTitle?: InputMaybe<StringFilter>;
  infoLabel?: InputMaybe<StringFilter>;
  onlyWorkLabel?: InputMaybe<StringFilter>;
  columnTitles?: InputMaybe<SiteColumnTitlesFilter>;
  biography?: InputMaybe<SiteBiographyFilter>;
  shortStories?: InputMaybe<SiteShortStoriesFilter>;
  poems?: InputMaybe<SitePoemsFilter>;
  interviews?: InputMaybe<SiteInterviewsFilter>;
  references?: InputMaybe<SiteReferencesFilter>;
  contactLinks?: InputMaybe<SiteContactLinksFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
};

export type SiteColumnTitlesMutation = {
  shortStories?: InputMaybe<Scalars['String']['input']>;
  poems?: InputMaybe<Scalars['String']['input']>;
  interviews?: InputMaybe<Scalars['String']['input']>;
  biography?: InputMaybe<Scalars['String']['input']>;
  references?: InputMaybe<Scalars['String']['input']>;
  contact?: InputMaybe<Scalars['String']['input']>;
};

export type SiteBiographyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type SiteShortStoriesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type SitePoemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type SiteInterviewsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type SiteReferencesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type SiteContactLinksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  siteTitle?: InputMaybe<Scalars['String']['input']>;
  infoLabel?: InputMaybe<Scalars['String']['input']>;
  onlyWorkLabel?: InputMaybe<Scalars['String']['input']>;
  columnTitles?: InputMaybe<SiteColumnTitlesMutation>;
  biography?: InputMaybe<Array<InputMaybe<SiteBiographyMutation>>>;
  shortStories?: InputMaybe<Array<InputMaybe<SiteShortStoriesMutation>>>;
  poems?: InputMaybe<Array<InputMaybe<SitePoemsMutation>>>;
  interviews?: InputMaybe<Array<InputMaybe<SiteInterviewsMutation>>>;
  references?: InputMaybe<Array<InputMaybe<SiteReferencesMutation>>>;
  contactLinks?: InputMaybe<Array<InputMaybe<SiteContactLinksMutation>>>;
};

export type SitePartsFragment = { __typename: 'Site', siteTitle: string, infoLabel: string, onlyWorkLabel: string, columnTitles?: { __typename: 'SiteColumnTitles', shortStories?: string | null, poems?: string | null, interviews?: string | null, biography?: string | null, references?: string | null, contact?: string | null } | null, biography?: Array<{ __typename: 'SiteBiography', title: string, text: string } | null> | null, shortStories?: Array<{ __typename: 'SiteShortStories', title: string, text: string } | null> | null, poems?: Array<{ __typename: 'SitePoems', title: string, text: string, image?: string | null } | null> | null, interviews?: Array<{ __typename: 'SiteInterviews', title: string, text: string } | null> | null, references?: Array<{ __typename: 'SiteReferences', title: string, text: string } | null> | null, contactLinks?: Array<{ __typename: 'SiteContactLinks', title: string, text: string } | null> | null };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, siteTitle: string, infoLabel: string, onlyWorkLabel: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, columnTitles?: { __typename: 'SiteColumnTitles', shortStories?: string | null, poems?: string | null, interviews?: string | null, biography?: string | null, references?: string | null, contact?: string | null } | null, biography?: Array<{ __typename: 'SiteBiography', title: string, text: string } | null> | null, shortStories?: Array<{ __typename: 'SiteShortStories', title: string, text: string } | null> | null, poems?: Array<{ __typename: 'SitePoems', title: string, text: string, image?: string | null } | null> | null, interviews?: Array<{ __typename: 'SiteInterviews', title: string, text: string } | null> | null, references?: Array<{ __typename: 'SiteReferences', title: string, text: string } | null> | null, contactLinks?: Array<{ __typename: 'SiteContactLinks', title: string, text: string } | null> | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, siteTitle: string, infoLabel: string, onlyWorkLabel: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, columnTitles?: { __typename: 'SiteColumnTitles', shortStories?: string | null, poems?: string | null, interviews?: string | null, biography?: string | null, references?: string | null, contact?: string | null } | null, biography?: Array<{ __typename: 'SiteBiography', title: string, text: string } | null> | null, shortStories?: Array<{ __typename: 'SiteShortStories', title: string, text: string } | null> | null, poems?: Array<{ __typename: 'SitePoems', title: string, text: string, image?: string | null } | null> | null, interviews?: Array<{ __typename: 'SiteInterviews', title: string, text: string } | null> | null, references?: Array<{ __typename: 'SiteReferences', title: string, text: string } | null> | null, contactLinks?: Array<{ __typename: 'SiteContactLinks', title: string, text: string } | null> | null } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  siteTitle
  infoLabel
  onlyWorkLabel
  columnTitles {
    __typename
    shortStories
    poems
    interviews
    biography
    references
    contact
  }
  biography {
    __typename
    title
    text
  }
  shortStories {
    __typename
    title
    text
  }
  poems {
    __typename
    title
    text
    image
  }
  interviews {
    __typename
    title
    text
  }
  references {
    __typename
    title
    text
  }
  contactLinks {
    __typename
    title
    text
  }
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/6e9d8786-5e32-4820-8485-ced9b0412518/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  